formspree_form_id: formspree_form_id
name: CyberDucky
title: Cyber Security Research
description: Cyber Security Research, in the form of videos, articles, and
  anything you can think of!
tags:
  - blog
  - cybersecurity
  - cyberducky
  - hacking
  - cyber
  - research
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
